### ISSUE TITLE
Tests failing due to 'WebDriver' object having no attribute 'find_elements_by_css_selector'

### ISSUE THREAD

**Issue by msp-platforme** [ripe-tech/ripe-rainbow#130]
## Description

- The automatic tests are failing and sometimes we don't have build artifacts to understand why (example: builds 2813 and 2814)
- The stacktrace we have for all failing tests on build 2812 and previous is
  `AttributeError: 'WebDriver' object has no attribute 'find_elements_by_css_selector'`
## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Rainbow can find elements by css selectors. |
| **Observed** | Apparently, at this point Rainbow can't find elements by css selectors. |

## Repro Steps

1. Open https://jenkins.platforme.com/job/ripe-tests/2812/
2. Open "Build Artifacts"
3. Open stacktraces
4. Open stacktrace of any failing test

## Example of a stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/test_cases.py", line 110, in run_test
    test()
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/decorators.py", line 28, in interceptor
    return function(*args, **kwargs)
  File "/var/jenkins_home/workspace/ripe-tests/src/ripe_tests/white/interactions.py", line 84, in previous_page_return_label
    self.set_previous_page()
  File "/var/jenkins_home/workspace/ripe-tests/src/ripe_tests/white/interactions.py", line 30, in set_previous_page
    self.waits.visible(".label-next-left-value", text="$ 70.00")
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/waits.py", line 64, in visible
    return self.until(
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/waits.py", line 9, in until
    return self.driver.wrap_outer(
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/interactive/drivers.py", line 464, in wrap_outer
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/waits.py", line 10, in <lambda>
    lambda: self.driver._wait(timeout = timeout).until(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/support/wait.py", line 81, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/waits.py", line 11, in <lambda>
    lambda *args: self.driver.wrap_inner(method, *args),
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/interactive/drivers.py", line 482, in wrap_inner
    try: return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/waits.py", line 65, in <lambda>
    lambda d: self._get_element(
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/waits.py", line 110, in _get_element
    element = self.logic.get(selector, condition = condition)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/logic.py", line 160, in get
    matching = self.find(selector, condition = condition)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/domain/base/logic.py", line 181, in find
    elements = self.driver.safe(self.driver.find_elements, selector)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/interactive/drivers.py", line 151, in safe
    return self.wrap_outer(self.wrap_inner, method, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/interactive/drivers.py", line 464, in wrap_outer
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/interactive/drivers.py", line 482, in wrap_inner
    try: return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ripe_rainbow/interactive/drivers.py", line 295, in find_elements
    return self.instance.find_elements_by_css_selector(selector)
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_css_selector'
```

**Comment by 3rdvision** [comment]
@3rdvision Yes, I'll take care of this one

**Comment by 3rdvision** [comment]
A quick google search suggests we might be using deprecated methods `find_element_by_*` and `find_elements_by_*`. This is probably the cause - the use of the deprecated `find_elements_by_css_selector` as the error also suggests.
